-- Auth schema: users, sessions, and role constraint

-- Users table
create table if not exists users (
    id bigserial primary key,
    email text not null unique,
    password_hash text not null,
    first_name text,
    last_name text,
    role text not null default 'REP', -- OWNER, REP, ESTIMATOR, PM, FOREMAN, OFFICE, CUSTOMER
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint users_role_chk check (role in ('OWNER','REP','ESTIMATOR','PM','FOREMAN','OFFICE','CUSTOMER'))
);

create index if not exists users_email_idx on users(email);

-- Sessions table
create table if not exists sessions (
    id text primary key, -- generated by server via crypto.randomUUID()
    user_id bigint not null references users(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index if not exists sessions_user_id_idx on sessions(user_id);
create index if not exists sessions_expires_at_idx on sessions(expires_at);


